nickname: angry-gopnick-and-bat
server: rrrrrrrrrrrrrrrrrrrrrrr
probability: 1000
channels:
  - "#agab"
reasons:
  - "I simply don't like you"
  - "I felt like it"
  - "Stop. Talking."
  - "Yup, just like that"
  - "Please, take it personally"
